services:
  
  # --------------------------------------------------------------------------
  # Backend API
  # --------------------------------------------------------------------------

  backend:
    build: 
      context: ./backend      # Đường dẫn tới thư mục chứa code và Dockerfile
      dockerfile: Dockerfile  # Tên file Dockerfile (mặc định)
    image: backend_image:local # Đặt tên cho image sau khi build xong ở máy bạn
    container_name: backend_cont
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      MONGODB_DB: haui_fitness_score
    ports:
      - "8888:8888"
    networks:
      - app-network
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_started


  # --------------------------------------------------------------------------
  # MongoDB
  # --------------------------------------------------------------------------

  mongodb:
    image: mongo:7
    container_name: fitness-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: haui_fitness_score
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "--eval",
          "db.adminCommand('ping').ok"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  # --------------------------------------------------------------------------
  # Redis
  # --------------------------------------------------------------------------

  redis:
    image: redis:7
    container_name: fitness-redis
    restart: unless-stopped
    command:
      - redis-server
      - --requirepass
      - "optivisionlab"
      - --notify-keyspace-events
      - "KEA"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "-a",
          "optivisionlab",
          "ping"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


  # --------------------------------------------------------------------------
  # MinIO
  # --------------------------------------------------------------------------

  minio:
    image: minio/minio:latest
    container_name: fitness-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: "password123"
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network

# ----------------------------------------------------------------------------
# Volumes
# ----------------------------------------------------------------------------

volumes:
  mongodb_data:
  redis_data:
  minio_data:


# ----------------------------------------------------------------------------
# Networks
# ----------------------------------------------------------------------------

networks:
  app-network:
    driver: bridge