import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./provider";
import { ThemeProvider } from "@/components/theme-provider";
import { ReduxProvider } from "@/redux/provider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Website chấm điểm thể dục",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <ReduxProvider>{children}</ReduxProvider>
          </Providers>
        </ThemeProvider>
        <Toaster
          richColors
          toastOptions={{
            className: "rounded-md px-4 py-2 font-medium shadow-lg",
            success: {
              style: {
                background: "#22c55e",
                color: "#fff",
              },
            },
            error: {
              style: {
                background: "#ef4444",
                color: "#fff",
              },
            },
            warning: {
              style: {
                background: "#facc15",
                color: "#000",
              },
            },
          }}
        />
      </body>
    </html>
  );
}
