import { TeacherClass } from './teacher.model';

export const INITIAL_TEACHER_CLASSES: TeacherClass[] = [
  {
    id: 'pickleball-01',
    code: 'FIT-PB01',
    name: 'Pickleball căn bản & nâng cao',
    semester: 'Học kỳ 1 - Năm học 2026-2027',
    schedule: 'Thứ 3, Tiết 1 - 3 (07:00 - 09:30)',
    location: 'Sân Pickleball - Khu Thể thao ĐH Công nghiệp Hà Nội',
    studentCount: 40,
    maxStudents: 40,
    progressSessions: 12,
    totalSessions: 15,
    status: 'active',
    iconType: 'pickleball',
    teacherName: 'ThS. Đặng Văn Long',
    teacherCode: 'GV2026001',
    isPracticeLocked: false,
    isSubmissionLocked: false,
    isFinalized: false,
    assessments: [
      {
        id: 'tx1',
        name: 'Đánh giá Thường xuyên 1 (TX1) - Kỹ thuật Giao bóng',
        type: 'tx1',
        weight: 15,
        gradingMethod: 'AI chấm tự động + GV hiệu chỉnh',
        timeLimit: '30 giây / lượt',
        openTime: '01/09/2026 08:00',
        closeTime: '25/09/2026 23:59',
        submittedCount: 40,
        totalCount: 40,
        isLocked: true,
        status: 'graded'
      },
      {
        id: 'tx2',
        name: 'Đánh giá Thường xuyên 2 (TX2) - Di chuyển & Đỡ bóng (Dink shot)',
        type: 'tx2',
        weight: 15,
        gradingMethod: 'AI chấm tự động qua video',
        timeLimit: '45 giây / lượt',
        openTime: '01/10/2026 08:00',
        closeTime: '20/10/2026 23:59',
        submittedCount: 38,
        totalCount: 40,
        isLocked: false,
        status: 'open'
      },
      {
        id: 'midterm',
        name: 'Kiểm tra Giữa kỳ - Phối hợp Đánh đôi & Chiến thuật sân',
        type: 'midterm',
        weight: 30,
        gradingMethod: 'Giáo viên chấm trực tiếp kết hợp AI phân tích',
        timeLimit: '2 phút / trận đấu thử',
        openTime: '25/10/2026 07:30',
        closeTime: '05/11/2026 23:59',
        submittedCount: 37,
        totalCount: 40,
        isLocked: false,
        status: 'open'
      },
      {
        id: 'final',
        name: 'Đánh giá Cuối kỳ - Thực hành Kỹ năng toàn diện',
        type: 'final',
        weight: 40,
        gradingMethod: 'Hội đồng Bộ môn GDTC chấm',
        timeLimit: '3 phút / sinh viên',
        openTime: '15/11/2026 07:00',
        closeTime: '20/11/2026 17:00',
        submittedCount: 0,
        totalCount: 40,
        isLocked: true,
        status: 'locked'
      }
    ],
    students: [
      {
        id: 'sv-001',
        studentCode: '2022601001',
        fullName: 'Nguyễn Văn An',
        majorClass: 'KTPM01-K17',
        tx1Score: 8.5,
        tx2Score: 9.0,
        midtermScore: 8.5,
        finalScore: null,
        finalAvgScore: 8.7,
        letterGrade: 'B+',
        resultStatus: 'pass',
        submissions: {
          tx1: {
            attemptNo: 2,
            submittedAt: '12/09/2026 09:15',
            duration: '00:28',
            aiScore: 8.3,
            aiFeedback: 'Tư thế phát bóng đúng chuẩn, điểm tiếp xúc bóng chính xác 92%.',
            teacherScore: 8.5,
            teacherComment: 'Động tác dứt khoát, duy trì phong độ tốt.',
            status: 'graded'
          },
          tx2: {
            attemptNo: 1,
            submittedAt: '15/10/2026 14:30',
            duration: '00:44',
            aiScore: 9.0,
            aiFeedback: 'Bước chân di chuyển linh hoạt, dink bóng qua lưới mượt mà.',
            teacherScore: 9.0,
            status: 'graded'
          }
        }
      },
      {
        id: 'sv-002',
        studentCode: '2022601002',
        fullName: 'Trần Thị Bích',
        majorClass: 'HTTT02-K17',
        tx1Score: 9.0,
        tx2Score: 9.5,
        midtermScore: 9.0,
        finalScore: null,
        finalAvgScore: 9.2,
        letterGrade: 'A',
        resultStatus: 'pass',
        submissions: {
          tx1: {
            attemptNo: 1,
            submittedAt: '10/09/2026 10:20',
            duration: '00:29',
            aiScore: 9.0,
            aiFeedback: 'Độ xoáy bóng tốt, góc đón bóng chuẩn xác.',
            teacherScore: 9.0,
            status: 'graded'
          },
          tx2: {
            attemptNo: 2,
            submittedAt: '14/10/2026 16:15',
            duration: '00:45',
            aiScore: 9.5,
            aiFeedback: 'Cảm giác bóng rất tốt, phản xạ nhanh nhạy.',
            teacherScore: 9.5,
            status: 'graded'
          }
        }
      },
      {
        id: 'sv-003',
        studentCode: '2022601003',
        fullName: 'Lê Hoàng Cường',
        majorClass: 'KHMT01-K17',
        tx1Score: 7.0,
        tx2Score: 7.5,
        midtermScore: 6.5,
        finalScore: null,
        finalAvgScore: 7.0,
        letterGrade: 'B',
        resultStatus: 'pass',
        submissions: {
          tx1: {
            attemptNo: 3,
            submittedAt: '22/09/2026 15:40',
            duration: '00:30',
            aiScore: 7.0,
            aiFeedback: 'Cần hạ thấp trọng tâm khi đón bóng.',
            teacherScore: 7.0,
            status: 'graded'
          }
        }
      },
      {
        id: 'sv-004',
        studentCode: '2022601004',
        fullName: 'Phạm Minh Đức',
        majorClass: 'KTPM03-K17',
        tx1Score: 5.5,
        tx2Score: 6.0,
        midtermScore: 5.0,
        finalScore: null,
        finalAvgScore: 5.5,
        letterGrade: 'C',
        resultStatus: 'warning',
        submissions: {
          tx1: {
            attemptNo: 1,
            submittedAt: '24/09/2026 21:10',
            duration: '00:30',
            aiScore: 5.5,
            aiFeedback: 'Lỗi phát bóng chạm lưới 2 lần. Cần cải thiện lực tay.',
            teacherScore: 5.5,
            status: 'graded'
          }
        }
      },
      {
        id: 'sv-005',
        studentCode: '2022601005',
        fullName: 'Đỗ Thị Hương Giang',
        majorClass: 'CNTT04-K17',
        tx1Score: 8.0,
        tx2Score: 8.5,
        midtermScore: 8.0,
        finalScore: null,
        finalAvgScore: 8.2,
        letterGrade: 'B+',
        resultStatus: 'pass'
      },
      {
        id: 'sv-006',
        studentCode: '2022601006',
        fullName: 'Vũ Đức Hải',
        majorClass: 'ATTT01-K17',
        tx1Score: 9.5,
        tx2Score: 9.0,
        midtermScore: 9.5,
        finalScore: null,
        finalAvgScore: 9.3,
        letterGrade: 'A',
        resultStatus: 'pass'
      },
      {
        id: 'sv-007',
        studentCode: '2022601007',
        fullName: 'Hoàng Ngọc Mai',
        majorClass: 'KTPM02-K17',
        tx1Score: 6.5,
        tx2Score: 7.0,
        midtermScore: 7.0,
        finalScore: null,
        finalAvgScore: 6.8,
        letterGrade: 'C+',
        resultStatus: 'pass'
      },
      {
        id: 'sv-008',
        studentCode: '2022601008',
        fullName: 'Ngô Quốc Nam',
        majorClass: 'DTVT01-K17',
        tx1Score: 4.0,
        tx2Score: null,
        midtermScore: null,
        finalScore: null,
        finalAvgScore: 4.0,
        letterGrade: 'D',
        resultStatus: 'fail'
      },
      {
        id: 'sv-009',
        studentCode: '2022601009',
        fullName: 'Bùi Thanh Phong',
        majorClass: 'KTPM01-K17',
        tx1Score: 8.0,
        tx2Score: 8.0,
        midtermScore: 8.5,
        finalScore: null,
        finalAvgScore: 8.2,
        letterGrade: 'B+',
        resultStatus: 'pass'
      },
      {
        id: 'sv-010',
        studentCode: '2022601010',
        fullName: 'Đoàn Quỳnh Như',
        majorClass: 'HTTT01-K17',
        tx1Score: 9.0,
        tx2Score: 8.5,
        midtermScore: 9.0,
        finalScore: null,
        finalAvgScore: 8.8,
        letterGrade: 'A',
        resultStatus: 'pass'
      }
    ]
  },
  {
    id: 'chay-ben-02',
    code: 'FIT-RUN02',
    name: 'Điền kinh & Chạy cự ly trung bình',
    semester: 'Học kỳ 1 - Năm học 2026-2027',
    schedule: 'Thứ 5, Tiết 7 - 9 (12:30 - 15:00)',
    location: 'Sân Vận động Trường ĐH Công nghiệp Hà Nội',
    studentCount: 38,
    maxStudents: 40,
    progressSessions: 14,
    totalSessions: 15,
    status: 'pending_finalize',
    iconType: 'chay',
    teacherName: 'ThS. Đặng Văn Long',
    teacherCode: 'GV2026001',
    isPracticeLocked: true,
    isSubmissionLocked: true,
    isFinalized: false,
    assessments: [
      {
        id: 'tx1',
        name: 'Đánh giá TX1 - Kỹ thuật xuất phát & chạy 100m',
        type: 'tx1',
        weight: 20,
        gradingMethod: 'AI nhận diện chuyển động & đo thời gian',
        timeLimit: '20 giây',
        openTime: '05/09/2026 08:00',
        closeTime: '20/09/2026 23:59',
        submittedCount: 38,
        totalCount: 38,
        isLocked: true,
        status: 'graded'
      },
      {
        id: 'tx2',
        name: 'Đánh giá TX2 - Kỹ thuật chạy bền 800m / 1500m',
        type: 'tx2',
        weight: 20,
        gradingMethod: 'Đo nhịp tim, sải chân & thời gian AI',
        timeLimit: '6 phút',
        openTime: '01/10/2026 08:00',
        closeTime: '15/10/2026 23:59',
        submittedCount: 38,
        totalCount: 38,
        isLocked: true,
        status: 'graded'
      },
      {
        id: 'midterm',
        name: 'Kiểm tra Giữa kỳ - Đánh giá sức bền tim mạch',
        type: 'midterm',
        weight: 20,
        gradingMethod: 'Giáo viên & AI kết hợp chấm',
        timeLimit: '8 phút',
        openTime: '20/10/2026 08:00',
        closeTime: '30/10/2026 23:59',
        submittedCount: 38,
        totalCount: 38,
        isLocked: true,
        status: 'graded'
      },
      {
        id: 'final',
        name: 'Thi Cuối kỳ - Chạy tiêu chuẩn thể lực quốc gia',
        type: 'final',
        weight: 40,
        gradingMethod: 'Bộ môn chấm trực tiếp',
        timeLimit: '10 phút',
        openTime: '05/11/2026 07:00',
        closeTime: '10/11/2026 17:00',
        submittedCount: 38,
        totalCount: 38,
        isLocked: true,
        status: 'graded'
      }
    ],
    students: [
      {
        id: 'sv-201',
        studentCode: '2022602001',
        fullName: 'Nguyễn Tiến Dũng',
        majorClass: 'KTPM01-K17',
        tx1Score: 9.0,
        tx2Score: 8.5,
        midtermScore: 9.0,
        finalScore: 8.5,
        finalAvgScore: 8.7,
        letterGrade: 'A',
        resultStatus: 'pass'
      },
      {
        id: 'sv-202',
        studentCode: '2022602002',
        fullName: 'Lê Thu Hà',
        majorClass: 'HTTT01-K17',
        tx1Score: 8.0,
        tx2Score: 8.0,
        midtermScore: 7.5,
        finalScore: 8.0,
        finalAvgScore: 7.9,
        letterGrade: 'B',
        resultStatus: 'pass'
      },
      {
        id: 'sv-203',
        studentCode: '2022602003',
        fullName: 'Vũ Quốc Khánh',
        majorClass: 'KHMT02-K17',
        tx1Score: 7.5,
        tx2Score: 7.0,
        midtermScore: 7.5,
        finalScore: 7.0,
        finalAvgScore: 7.2,
        letterGrade: 'B',
        resultStatus: 'pass'
      }
    ]
  },
  {
    id: 'pickleball-02',
    code: 'FIT-PB02',
    name: 'Pickleball thi đấu & Trọng tài',
    semester: 'Học kỳ 1 - Năm học 2026-2027',
    schedule: 'Thứ 6, Tiết 4 - 6 (09:40 - 12:00)',
    location: 'Sân Pickleball - Khu Thể thao ĐH Công nghiệp Hà Nội',
    studentCount: 42,
    maxStudents: 42,
    progressSessions: 15,
    totalSessions: 15,
    status: 'finalized',
    iconType: 'pickleball',
    teacherName: 'ThS. Đặng Văn Long',
    teacherCode: 'GV2026001',
    isPracticeLocked: true,
    isSubmissionLocked: true,
    isFinalized: true,
    finalizedAt: '12/11/2026 16:45',
    finalizedBy: 'ThS. Đặng Văn Long (GV2026001)',
    assessments: [
      {
        id: 'tx1',
        name: 'TX1 - Quy tắc giao nhận và đếm điểm',
        type: 'tx1',
        weight: 15,
        gradingMethod: 'AI chấm tự động',
        timeLimit: '30 giây',
        openTime: '01/09/2026',
        closeTime: '20/09/2026',
        submittedCount: 42,
        totalCount: 42,
        isLocked: true,
        status: 'graded'
      },
      {
        id: 'tx2',
        name: 'TX2 - Điều hành trận đấu mô phỏng',
        type: 'tx2',
        weight: 15,
        gradingMethod: 'GV chấm',
        timeLimit: '1 phút',
        openTime: '01/10/2026',
        closeTime: '20/10/2026',
        submittedCount: 42,
        totalCount: 42,
        isLocked: true,
        status: 'graded'
      },
      {
        id: 'midterm',
        name: 'Giữa kỳ - Kỹ thuật tấn công trên lưới (Smash)',
        type: 'midterm',
        weight: 30,
        gradingMethod: 'AI + GV',
        timeLimit: '2 phút',
        openTime: '25/10/2026',
        closeTime: '05/11/2026',
        submittedCount: 42,
        totalCount: 42,
        isLocked: true,
        status: 'graded'
      },
      {
        id: 'final',
        name: 'Cuối kỳ - Giải đấu tổng kết lớp',
        type: 'final',
        weight: 40,
        gradingMethod: 'Hội đồng chấm',
        timeLimit: '5 phút',
        openTime: '08/11/2026',
        closeTime: '12/11/2026',
        submittedCount: 42,
        totalCount: 42,
        isLocked: true,
        status: 'graded'
      }
    ],
    students: [
      {
        id: 'sv-301',
        studentCode: '2022603001',
        fullName: 'Hoàng Văn Thái',
        majorClass: 'KTPM02-K17',
        tx1Score: 9.0,
        tx2Score: 9.0,
        midtermScore: 9.5,
        finalScore: 9.0,
        finalAvgScore: 9.2,
        letterGrade: 'A',
        resultStatus: 'pass'
      },
      {
        id: 'sv-302',
        studentCode: '2022603002',
        fullName: 'Phạm Thị Thùy Dung',
        majorClass: 'HTTT01-K17',
        tx1Score: 8.5,
        tx2Score: 8.0,
        midtermScore: 8.5,
        finalScore: 8.5,
        finalAvgScore: 8.4,
        letterGrade: 'B+',
        resultStatus: 'pass'
      }
    ]
  },
  {
    id: 'the-duc-nhyp-dieu-03',
    code: 'FIT-AER03',
    name: 'Thể dục nhịp điệu & Aerobic hình thể',
    semester: 'Học kỳ 1 - Năm học 2026-2027',
    schedule: 'Thứ 7, Tiết 1 - 3 (07:00 - 09:30)',
    location: 'Nhà thi đấu Đa năng - Tầng 3',
    studentCount: 40,
    maxStudents: 40,
    progressSessions: 9,
    totalSessions: 15,
    status: 'active',
    iconType: 'fitness',
    teacherName: 'ThS. Đặng Văn Long',
    teacherCode: 'GV2026001',
    isPracticeLocked: false,
    isSubmissionLocked: false,
    isFinalized: false,
    assessments: [
      {
        id: 'tx1',
        name: 'TX1 - Động tác vũ đạo cơ bản 8 nhịp',
        type: 'tx1',
        weight: 20,
        gradingMethod: 'AI nhận diện khớp & nhịp điệu',
        timeLimit: '45 giây',
        openTime: '10/09/2026',
        closeTime: '30/09/2026',
        submittedCount: 40,
        totalCount: 40,
        isLocked: true,
        status: 'graded'
      },
      {
        id: 'tx2',
        name: 'TX2 - Động tác bật nhảy & kiểm soát thăng bằng',
        type: 'tx2',
        weight: 20,
        gradingMethod: 'AI nhận diện tư thế',
        timeLimit: '1 phút',
        openTime: '05/10/2026',
        closeTime: '25/10/2026',
        submittedCount: 35,
        totalCount: 40,
        isLocked: false,
        status: 'open'
      },
      {
        id: 'midterm',
        name: 'Giữa kỳ - Bài tập nhóm 4 người theo nhạc',
        type: 'midterm',
        weight: 20,
        gradingMethod: 'GV chấm',
        timeLimit: '2 phút',
        openTime: '01/11/2026',
        closeTime: '15/11/2026',
        submittedCount: 0,
        totalCount: 40,
        isLocked: false,
        status: 'open'
      },
      {
        id: 'final',
        name: 'Cuối kỳ - Bài biểu diễn hoàn chỉnh',
        type: 'final',
        weight: 40,
        gradingMethod: 'Hội đồng chấm',
        timeLimit: '3 phút',
        openTime: '25/11/2026',
        closeTime: '30/11/2026',
        submittedCount: 0,
        totalCount: 40,
        isLocked: true,
        status: 'locked'
      }
    ],
    students: [
      {
        id: 'sv-401',
        studentCode: '2022604001',
        fullName: 'Đặng Mai Linh',
        majorClass: 'KTPM02-K17',
        tx1Score: 9.0,
        tx2Score: 8.5,
        midtermScore: null,
        finalScore: null,
        finalAvgScore: 8.8,
        letterGrade: 'A',
        resultStatus: 'pass'
      }
    ]
  }
];
